### PR TITLE
Cleanup the initial bookmarks

### PR DESCRIPTION
**Pull request by Grociu**
The initial bookmarks have double entries for Japan and Western Europe.
This makes each Missions Expanded bookmarks unique.

I deleted the original commit files and left newer bookmarks untouched. The remaining files might need rearranging (renaming) to a consistent order.

### CODE REVIEW

**Comment by stackpoint** [comment]
I haven't had a chance to run this but the reason the vanilla bookmark was added back in was because the default ME bookmark had your screen start in non-europe and that was upsetting to some people. Where is the default bookmark with this change?

**Comment by mellester** [comment]
I would recommend commenting it out. The reason being people that use winmerge tend to in include deleted tekst .

**Comment by Grociu** [comment]
The 'Rise of the Ottomans' bookmark on top was left in. I deleted two duplicates from ME.

**Comment by stackpoint** [comment]
I can pull this into the modpack but you may have to keep an eye on it in the future because as @mellester said: "people that use winmerge tend to in include deleted text" or you can update it to be an empty/commented file.

**Comment by Grociu** [comment]
Readded the files and content, and commented it out. Works ingame.

**Pull request merged**
