### PR TITLE
American Trade 2.0.1 Manilla

### PR DESCRIPTION
**Pull request by mistakingover**
Minor fixes on localization.

(GitHub apparently thinks the Manilla patch was not merged into the master.)

### CODE REVIEW

**Comment by Grociu** [comment]
> (GitHub apparently thinks the Manilla patch was not merged into the master.)

By the nature of this tool, your `mistakingover:americas_tradenodes` branch is detached from master at point of creation. Any new update to this branch will update the branch ONLY as it's a separate entity from master. When you make a Pull Request, you submit your whole branch, from the point of detachment.
The usual way these things are done is to delete your branch when it's merged to master, and creating a new one for new commits.
There's probably some git magic you can do to merge a branch on your local fork to avoid deleting, but I'm just used to this way of doing things.

**Comment by stackpoint** [comment]
We can squash and merge this pull to avoid the extra commits but I believe @Grociu is correct that you should be deleting the pull branch after a merge.

**Comment by mellester** [comment]
Or sqaush the entire branch but making a new branch is ussaly faster

**Comment by stackpoint** [comment]
@mistakingover I know you are a bit unfamiliar with git so it might be easier for you to use the [Pull App](https://github.com/wei/pull#readme) to keep the master branches up to date. Although this will require you to keep all your work off your fork's master branch as it will overwrite any changes.

**Pull request merged**
