### PR TITLE
Tradenodes america

### PR DESCRIPTION
**Pull request by mistakingover**
Modifies the trade node network in the Americas to make the Caribbean Trade Node the main one. Changes can be seen below, as the pathing still needs some fixes.

Still needs fixing the pathing between nodes:
st_lawrence to chesapeake
james_bay to north_sea
chesapeake to carribean_trade
brazil to carribean_trade
patagonia to lima
carribean_trade to english_channel

The caribbean trade node screen seems to be too crowded with tabs from the overflowing of incoming nodes.

### CODE REVIEW

**Review by stackpoint — CHANGES_REQUESTED** [review]
I am getting the following errors:
```
[tradenodedefinition.cpp:59]: Chesapeake Bay=>carribean_trade ( ERROR: Trade nodes must always be defined so that an outgoing is defined after in the file, or we get processing errors)
[tradenodedefinition.cpp:59]: Gulf of St. Lawrence=>chesapeake_bay ( ERROR: Trade nodes must always be defined so that an outgoing is defined after in the file, or we get processing errors)
```

Trade_nodes_with_arrows2 1

**Comment by mistakingover** [comment]
> I am getting the following errors:
> [tradenodedefinition.cpp:59]: Chesapeake Bay=>carribean_trade ( ERROR: Trade nodes must always be defined so that an outgoing is defined after in the file, or we get processing errors)
> [tradenodedefinition.cpp:59]: Gulf of St. Lawrence=>chesapeake_bay ( ERROR: Trade nodes must always be defined so that an outgoing is defined after in the file, or we get processing errors)

Will look into that. Game was working as intended when I loaded it. Will try uploading the changed file once again

**Comment by Grociu** [comment]
image

One of the routes goes off the map, please adjust.

**Comment by stackpoint** [comment]
Looks good so far. Was there any other general route changes you wanted to make that I could update the trade map screenshot with?

**Comment by mistakingover** [comment]
> One of the routes goes off the map, please adjust.

Fixed (was working as intended)

**Comment by mistakingover** [comment]
> Looks good so far. Was there any other general route changes you wanted to make that I could update the trade map screenshot with?

no other change in routing on new trade routes so far

**Pull request merged**
