### PR TITLE
Dogefeaturebranch

### PR DESCRIPTION
**Pull request by ComradDoge**
Add 10% increase for land maintenance. Works thematically with idea, isn't too burdening but enough to furter incentivize to lower your troops.

### CODE REVIEW

**Comment by stackpoint** [comment]
Would the AI understand this.

**Comment by ComradDoge** [comment]
Isnt the lowering troops dealt within the 7th idea through script triggers? So they would lower their troops no matter what

**Comment by stackpoint** [comment]
Not sure what you mean by that

**Comment by ComradDoge** [comment]
Are you worried the AI wont take the 10% increase in account to their economy?

**Comment by stackpoint** [comment]
I meant the reference to script triggers

**Comment by ComradDoge** [comment]
Don't see wehrpflicht6 anywhere in any event files and only wehrpflicht7 is checked in some so should be fine.

**Comment by stackpoint** [comment]
> Isnt the lowering troops dealt within the 7th idea through script triggers?

What did you mean by this

**Comment by ComradDoge** [comment]
Not gonna lie, I dunno. I think I was thinking of it from a player perspective or something and had weird idea about how AI handles it. For real, ignore that.

**Comment by stackpoint** [comment]
Negative modifier makes sense if the AI can avoid them but I don't think that's the case here.

**Pull request closed without merging**
