### PR TITLE
American Trade 1.2 Veracruz and Acapulco

### PR DESCRIPTION
**Pull request by mistakingover**
Fixes on map placements (cities, ports, units...)
Changes to map locations of trade nodes to better represent them.

New trade routes:
Mississippi River -> Mexico
Northern Andes -> Mexico

Storms on the Bermuda Triangle are now stronger.

### CODE REVIEW

**Comment by stackpoint** [comment]
> Storms on the Bermuda Triangle are now stronger.

How strong?

**Comment by mistakingover** [comment]
Real in-game picture

https://cdn.discordapp.com/attachments/701521158029181089/712762187906547832/SPOILER_20121012-103330.jpg

**Comment by stackpoint** [comment]
image

**Comment by mellester** [comment]
Nice picture

**Pull request merged**
