### PR TITLE
American Trade Nodes 0.2

### PR DESCRIPTION
**Pull request by mistakingover**
Upper Missouri area now belongs to the Mississipi Trade Node.
Greenland area now belongs to the Hudson Bay Trade Node.
Labrador area now belongs to the Hudson Bay Trade Node.
New Hampshire area now belongs to the St. Lawrence Trade Node.
East Yucatan area now belongs to the Caribbean Sea Trade Node.
Lower Guatemala Area now belongs to the Caribbean Sea Trade Node.

Panama Trade Node deleted and provinces merged in adjacent nodes as follows:
Cordillera Occidental, Bogota and Colombian Amazonas areas to Lima;
Province 837 (nicaragua) and Province 2640 (honduras) to Mexico Trade Node;
Coquivacoa, Costa Rica, Honduras (-2640), Western Llanos, Nicaragua (-837), and Panama areas to Caribbean Sea Trade Node.

Amazonas Trade Node deleted and provinces merged in Caribbean and Brazil Trade Nodes as follows:
Guiana, Upper Guiana, Suriname and Central Llanos areas to Caribbean Sea;
Amapa, Pontal, Grao Para, Amazon, Maranhao, Piaui areas to Brazil;
Wasteland Provinces 2936 (guiana), 1802 (western amazonas) and 1803 (eastern amazonas) to Brazil.

Mexico Province (Tenochtitlan) is now the location for the Mexico Trade Node, as should be.

Caribbean Sea Trade Node (carribean_trade) moved down on the code, should be above Bordeaux.
Hudson Bay Trade Node (james_bay) moved up on the code, should be below Amazonas.

Hudson Bay Trade Node (james_bay) now divided by area in the code for better visualization, like other nodes.
St. Lawrence Trade Node (st_lawrence) now divided by area in the code for better visualization, like other nodes.
Caribbean Sea Trade Node (carribean_trade) now divided by area in the code for better visualization, like other nodes.
Chesapeake Bay Trade Node (chesapeake_bay) now divided by area in the code for better visualization, like other nodes.
Mexico Trade Node (mexico) now divided by area in the code for better visualization, like other nodes.

Reorganized american nodes area divisions (above) to alphabetical order (disregarding area adjetives like "upper and lower" to better represent geographical location while still following alphabetical order). Trade Node Location (if inland) is first. Sea provinces always listed in the end.

Virginia area in the chesapeake_bay trade node is called countryroads_area in the code.
Hudson Valley in the chesapeake_bay trade node is called riverhudson_area in the code.
Piedmont Area in the chesapeake_bay trade node is called american_piedmont_area in the code.
East Cuba Area in carribean_sea trade node is called ecuba_area in the code.
West Cuba Area in carribean_sea trade node is called wcuba_area in the code.
East Florida Area in carribean_sea trade node is called eflorida_area in the code.
Central Llanos Area in carribean_sea trade node is called cllanos_area in the code.
East Llanos Area in carribean_sea trade node is called ellanos_area in the code.
Greater Antilles Area in carribean_sea trade node is called grantilles_area in the code.

Added Trade Route from Philippines to Caribbean Sea

### CODE REVIEW

**Comment by stackpoint** [comment]
Great work, even better documentation. Is there a reason you split Lenca (2640), Nicaragua (837) and Darien (2819) out the Caribbean node and out of their respective states' trade nodes?

I am a big proponent of having states' provinces being in the same node.

**Comment by mistakingover** [comment]
> Great work, even better documentation. Is there a reason you split Lenca (2640), Nicaragua (837) and Darien (2819) out the Caribbean node and out of their respective states' trade nodes?
> I am a big proponent of having states' provinces being in the same node.

Thanks. I'm still learning but makes me happy that my work has been improving these 2 days I've been actively programing out of classes.
The provinces of Lenca (2640), Nicaragua (837) and Darien (2819) have Pacific ports while the Caribbean Trade Node coastal provinces should all have ports on the Caribbean Sea.
As such, they were more linked with the pacific major ports of Acapulco (Mexico node) and Lima (Lima node) instead of connected to the Caribbean, as the Channel was not yet in place.

**Comment by stackpoint** [comment]
Okay, that makes sense. How does it sound to move those provinces out of those states and into a neighboring one that matches their trade node?

**Comment by mistakingover** [comment]
> Okay, that makes sense. How does it sound to move those provinces out of those states and into a neighboring ones?

I don't see a problem with states having different trade nodes on their provinces. This would make some european and asian trade nodes more difficult, as not all states should be fully present in one node. If needed be after testing, than this might prove difficult, as some states would be long lines following coastal provinces.
I think the best approach would be to wait and see how both the game and community react to states being divided on two trade nodes and make the changes accordingly.

**Comment by stackpoint** [comment]
Okay that's reasonable. Functionally, there isn't really a difference in having states provinces and trade nodes not match up, it just makes things more organized. 

Are you able to get the control parameters setup? I can make a fix for the trade route paths if you can't.

**Comment by mistakingover** [comment]
No path fixing this time. There should be no issues on this patch.

**Pull request merged**
