### PR TITLE
American Trade 2.0 Manilla

### PR DESCRIPTION
**Pull request by mistakingover**
New Pacific Islands Trade Node (pacific_islands):
- Areas: Eastern Polynesia, Northern Polynesia (-Aleut 979), Polynesia, West Micronesia, East Micronesia, Melanesia (-Rabaul 1236).
- Routes to: Mexico, Caribbean Sea, Philippines and Korea-Honshu.

Nippon Trade Node Rework:
- Renamed to Korea-Honshu (kr_hsh).
- Province 2111 moved from Manchuria to Korea-Honshu
- Provinces 2112 and 2113 moved from Beijing to Korea-Honshu.
- Taiwan area moved from Hangzhou to Korea-Honshu.
- Mexico -> Korea-Honshu removed.

New West Pacific Trade Node:
- Areas: Furdan, South Ilin Hala (729, 2105 and 4217), North Ilin Hala, East Heilongjiangord, West Heilongjiangord (2102), Sakhalin, Hokkaido, East Siberia Region. 
- Routes to: Korea-Honshu, Siberia.

Girin Trade Node Rework:
- Renamed to Southern Manchuria (smanchuria).
- Is now an inland node.
- Routes to: Korea-Honshu, Beijing, West Pacific.

Philippines Trade Node Rework:
- Renamed to Luzviminda (luzviminda).
- Fixed positioning of Trade Node Map Marker (buoy). Was wrongly placed on the Philippines Trench while the actual province being Visayan Sea.
- Changed the route to Caribbean Sea to Mexico as historical Manilla-Acapulco galeons.
- Fix to pathing to The Moluccas.

Australia Trade Node Rework:
- Renamed to Australasia.
- Fixes to pathing.
- Trade Node Map Marker moved to Lord Howe Island sea province.
- New trade route from Australasia to Chile.

Canton Trade Node Fixes:
- Better positioning to Canton Trade Node Map Marker (buoy), now at the mouth of the Pearl River.
- Fixed routes to: Philippines, Malacca, Hangzhou.

Fixes to positioning:
- Chilean Regions.
- Rechecking of Argentinian region.
- Easter Island.
- Panama Region.
- Caribbean Sea Region.
- Philippine Sea Region.
- Furdan province.

Fixes to Pathing:
- Panama transoceanic crossing.

Changes to seaport locations:
- Kaweskar port now in Magellan Strait sea province, to represent Punta Arenas.

Changes to localization:
- English, French, German and Spanish localization to Southern Manchuria, Korea-Honshu, Luzviminda, Australasia and Pacific Islands.

To devs only:
- To see if a province had its positioning checked, the Text Height should be at 1.20.

### CODE REVIEW

**Comment by mistakingover** [comment]
Issue:
[tradenodedefinition.cpp:59]: Luzviminda=>mexico ( ERROR: Trade nodes must always be defined so that an outgoing is defined after in the file, or we get processing errors)

Luzviminda (Philippines) is already before Mexico node, but the game keeps giving this error. I've looked into the code and couldn't find a reason.

**Comment by Grociu** [comment]
`mexico` is defined twice, at line 411 and 1870.

**Comment by mistakingover** [comment]
> mexico is defined twice, at line 411 and 1870.

You are correct.

**Review by mistakingover — COMMENTED** [review]
Is now ready for pull into master.

**Comment by stackpoint** [comment]
Reverse uno version: [00_tradenodes.txt](https://github.com/TheDivexz/excelmakesbelhappypack/files/4672432/00_tradenodes.txt)

**Pull request merged**
